### ISSUE TITLE
Request: OpenAPI example

### ISSUE THREAD

**Issue by alenhorvat** [ISAITB/shacl-validator#11]
Dear,

can you please provide a simple (minimal possible number of fields) representative example for the API call(s); I tried to replicate the calls from the example: https://github.com/ISAITB/shacl-validator/issues/10
but it's not clear how I should provide the inputs as string and/or base64 encoded values?

Would it be possible to get 1 simple example where input is a compact serialised JSON-LD and external validation is Turtle (either referenced or embedded).

Thank you!

**Comment by costas80** [comment]
We have a detailed [user and configuration guide](https://www.itb.ec.europa.eu/docs/guides/latest/validatingRDF/index.html) for our RDF validator. This covers all that is needed to create your own validator instance but also how to use a validator via its different APIs (the validators we manage such as the [generic SHACL validator](https://www.itb.ec.europa.eu/shacl/any/upload) are configurations of this).

As part of this documentation you will also find the [REST API user guide](https://www.itb.ec.europa.eu/docs/guides/latest/validatingRDF/index.html#validation-via-rest-web-service-api) that besides documenting all options provides examples including what you're looking for. It considers a demo "purchase order" configuration but if you replace "order" with "any" (or another configuration) you should get the idea. You can consider this as a complement to the [Swagger UI/Open API docs](https://www.itb.ec.europa.eu/shacl/swagger-ui/index.html).

Does this cover you?

**Comment by alenhorvat** [comment]
My request is even simpler; just adding a valid example to the OpenAPI/swagger specs;
One example would be:
```json
{
  "contentToValidate": "https://raw.githubusercontent.com/alenhorvat/public/main/pastebin/elm-ebsi-example.json",
  "contentSyntax": "application/ld+json",
  "embeddingMethod": "URL",
  "validationType": "any",
  "externalRules": [
    {
      "ruleSet": "https://raw.githubusercontent.com/european-commission-empl/European-Learning-Model/master/rdf/ontology/ELM.ttl",
      "embeddingMethod": "URL",
      "ruleSyntax": "text/turtle"
    }
  ]
}
```

Note: here I fixed the URLs and published the schema via jsDeliver so that the content type is correct.

Another example would be with "embeddingMethod" string and base64

**Comment by costas80** [comment]
Indeed - adding such examples directly in the Open API docs would be good. The only problem is that the validator's API differs depending on the domain in question ("any"), whether it has multiple validation types ("any"), whether it supports external rules etc. I'll see how we could provide these however to make sense for any configuration.

Let's keep this issue open until we update the docs. Like that I can let you know when the update is online and you can tell me what you think.

**Comment by alenhorvat** [comment]
This looks great! Thanks!
