### ISSUE TITLE
Show Results Only, Hide Form Elements

### ISSUE THREAD

**Issue by init-dcat-ap-de** [ISAITB/shacl-validator#2]
See https://github.com/GovDataOfficial/DCAT-AP.de-SHACL-Validation/issues/14:

> The validator is a single page application.
> 
> To better embed the validator inside an application it would be helpful to only show the results and to hide the form fields.
> 
> This could be implemented e.g. by a (hidden) form parameter `hide_form`.

And the following discussion.

**Comment by costas80** [comment]
Viewing the results in text form is the minimal UI would be interesting indeed. In general we try to keep the UI of the minimal UI as concise as possible and avoid adding any superfluous information. My proposal here would be to include two expandable sections in the display of the results, one containing the overview (i.e. what you see today - open by default) and the second one (closed by default) that includes the findings. This should keep the UI quite simple but allow you to review findings without needing to download the report.
