### ISSUE TITLE
When validating with URI, please trim input!

### ISSUE THREAD

**Issue by init-dcat-ap-de** [ISAITB/shacl-validator#6]
Repost from:
https://github.com/GovDataOfficial/DCAT-AP.de-SHACL-Validation/issues/18

When validating with URI, e.g. https://offenedaten.frankfurt.de/catalog.rdf?fq=name%3Ahauskoordinaten-franfurt
with a space at the end (that may happen when URI is copy&pasted), the validator breaks and gives an error:

> Bei der Validierung ist ein Fehler aufgetreten [Illegal character in query at index 79: 
> https://offenedaten.frankfurt.de/catalog.rdf?fq=name%3Ahauskoordinaten-franfurt ].

Please strip off any whitespaces of the input before processing.

**Comment by costas80** [comment]
The issue is now fixed and deployed in the online validator.

**Comment by costas80** [comment]
Issue confirmed as resolved by the original poster.
