### ISSUE TITLE
multi-architecture images

### ISSUE THREAD

**Issue by KristofVDB1** [ISAITB/shacl-validator#8]
I ran into some problems trying to run a docker container using the `isaitb/shacl-validator` image. The problem I'm getting is

```sh
[Too many errors, abort]
 qemu: uncaught target signal 6 (Aborted) - core dumped
```

**Dockerfile** 

```dockerfile
FROM isaitb/shacl-validator:latest
COPY resources /validator/resources/
ENV validator.resourceRoot /validator/resources/
```

**Server structure**
<img width="269" alt="Screenshot 2024-04-18 at 11 39 53" src="https://github.com/ISAITB/shacl-validator/assets/28532087/606b3355-4722-4b3b-af6e-a19175bb4416">

After running the `docker run -d --name po-validator -p 8080:8080 po-validator:latest` I received the following warning:
```sh
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
````

I am indeed running the Docker container from an Apple device, but since it only gave me a warning I wasn't sure if that is indeed the cause for the failing container. Is it possible to use this image from a `linux/arm64/v8` device?

**Comment by KristofVDB1** [comment]
@costas80 Thanks for the quick response! Looking forward to the update!

**Comment by costas80** [comment]
@KristofVDB1, we have now published multi-architecture variants for all our images on the Docker Hub. For now we provide `linux/amd64` (as was previously the case) and `linux/arm64` but we could potentially add others in the future if there is demand.

In your specific case, `linux/arm64/v8` is an alias for `linux/arm64`, so running `docker pull isaitb/shacl-validator` from your Apple device should get the correct image. If that does not work for some reason you can specify the platform explicitly through `docker pull --platform linux/arm64 isaitb/shacl-validator`.

Can you check and let me know if this update resolved your issue?

**Comment by KristofVDB1** [comment]
@costas80, really impressed with the speed of delivery. Props to you guys!

I tried to run the exact same setup as yesterday and it started without any issues now. I'll be doing some testing with it the upcoming week, but so far it looks good. If something comes up again related to the architecture, I'll reopen this issue.

Thanks!
